In [ ]:
import pandas as pd
import numpy as np

In [ ]:


#1.Create Arrays

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
#2.Array Operations

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a * b)

[11 22 33]
[10 40 90]


In [ ]:
#3.Zeros and Ones

print(np.zeros((2, 3)))
print(np.ones((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:

#4.Mean, Max, Min

data = np.array([10, 20, 30, 40])

print("Mean:", np.mean(data))
print("Max:", np.max(data))
print("Min:", np.min(data))

Mean: 25.0
Max: 40
Min: 10
